const employees = [
    {
        id: 'ckx1y1g0g0000qz6g0g0g0g0',
        employeeId: 'E001',
        firstName: 'John',
        lastName: 'Doe',
        position: 'Software Engineer',
        department: 'Engineering',
        email: 'john.doe@example.com',
    },
    {
        id: 'ckx1y1g0g0000qz6g0g0g0g1',
        employeeId: 'E002',
        firstName: 'Jane',
        lastName: 'Smith',
        position: 'Product Manager',
        department: 'Product',
        email: 'jane.smith@example.com',
    },
    {
        id: 'ckx1y1g0g0000qz6g0g0g0g2',
        employeeId: 'E003',
        firstName: 'Alice',
        lastName: 'Johnson',
        position: 'UX Designer',
        department: 'Design',
        email: 'alice.johnson@example.com',
    },
    {
        id: 'ckx1y1g0g0000qz6g0g0g0g3',
        employeeId: 'E004',
        firstName: 'Bob',
        lastName: 'Brown',
        position: 'Data Analyst',
        department: 'Analytics',
        email: 'bob.brown@example.com',
    },
    {
        id: 'ckx1y1g0g0000qz6g0g0g0g4',
        employeeId: 'E005',
        firstName: 'Charlie',
        lastName: 'Davis',
        position: 'HR Specialist',
        department: 'Human Resources',
        email: 'charlie.davis@example.com',
    },
];